resources:
- name: ci
  type: git
  source:
    uri: https://github.com/dalvarado/ci
    branch: master
    paths:
    - tasks
    - dockerfiles
    - vendor


- name: kiln
  type: git
  source:
    uri: git@github.com:dalvarado/kiln
    branch: master
    private_key: ((create_new_deploy_keys_private_here))
    ignore_paths:
    - version
    - README.md


- name: kiln-version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:dalvarado/kiln.git
    git_user: dalvarado@pivotal.io
    branch: master
    file: version
    username: dalvarado
    private_key: ((create_new_deploy_keys_private_here))
jobs:

# Kiln
- name: update-kiln-version
  plan:
  - in_parallel:
    - get: kiln-version
      params:
        bump: minor
  - put: kiln-version
    params:
      bump: minor

- name: create-kiln-release
  plan:
  - in_parallel:
    - get: ci
    - get: kiln
    - get: kiln-version
      trigger: true
      passed:
      - update-kiln-version
  - task: build
    file: ci/tasks/tooling/kiln/build/task.yml
    params:
      GITHUB_TOKEN: ((API_TOKEN_TO_UPDATE_RELEASE))
