---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalcfreleng/golang}

inputs:
- name: pcf-releng-ci
- name: kiln
- name: tile

run:
  path: pcf-releng-ci/tasks/tooling/kiln/integration-tests/task.sh
params:
  KILN_ACCEPTANCE_VARS_FILE_CONTENTS:
  PIVNET_TOKEN:

  PRODUCT_DIRECTORY: tile
