---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalcfreleng/golang}

inputs:
- name: pcf-releng-ci
- name: kiln

run:
  path: pcf-releng-ci/tasks/tooling/kiln/build-example-tile/task.sh
